### ISSUE TITLE
[REQUEST] Remove Bethesda Intro

### ISSUE THREAD

**Issue by ErraticFox** [tapcio/OneTweak#1]
Why not make one of my favorite tiny mods the best by just adding in the removal of the Bethesda Intro?

**Comment by Nucleoprotein** [comment]
In Skyrim is already done.
https://github.com/tapcio/OneTweak/blob/master/OneTweak/SkyrimHost.cpp#L51

For dev: it works by writing NULL at start of intro file name.

**Comment by ErraticFox** [comment]
Ah, I did not know about that. It doesn't say it on the mod page and I usually use another mod for it so I wouldn't have been able to notice if this mod did it. Sorry! :)

**Comment by L-a-n-g-o-l-i-e-r-s** [comment]
Would you mind doing this for FNV? Thanks!!
