### ISSUE TITLE
Please blobberish god investigate Skyrim stuttering/physics issues

### ISSUE THREAD

**Issue by mirh** [tapcio/OneTweak#2]
Which tbh is a game I don't even own, but hell it's not [bugged](http://pcgamingwiki.com/wiki/Thread:Talk:The_Elder_Scrolls_V:_Skyrim/Skyrim_runs_best_at_64Hz%3F/reply_%282%29).

**Comment by Nucleoprotein** [comment]
I really never bother to dig in this stuttering issue, but in most cases running game in window = butter smooth - mostly on AMD cards.

About physics issue seems to be related to tick rate of engine, I can look when I have a little (24h :stuck_out_tongue:) time to spends on debugging.

PS: DisableDriverMemoryManager things (which I think is D3DCREATE_DISABLE_DRIVER_MANAGEMENT flag) does nothing for AMD hardware as it NOT support managed resources (D3D9 cap D3DCAPS2_CANMANAGERESOURCE is off).

**Comment by mirh** [comment]
By the way, you might be interested to https://github.com/Kaldaien/FO4W/
